<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.2.1.352
*/

require_once('form_process.php');

$form = array(
	'subject' => 'contact Form 送出',
	'heading' => '新的表單送出',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => '已核取',
		'checkbox_unchecked' => '取消選取',
		'submitted_from' => '表單由此網站送出: %s',
		'submitted_by' => '訪客 IP 位址: %s',
		'too_many_submissions' => '此 IP 最近有太多送出記錄',
		'failed_to_send_email' => '傳送電子郵件失敗',
		'invalid_reCAPTCHA_private_key' => '無效的 reCAPTCHA 私密金鑰。',
		'invalid_field_type' => '不明的欄位類型「%s」。',
		'invalid_form_config' => '「%s」欄位有無效的設定。',
		'unknown_method' => '不明的伺服器要求方式'
	),
	'email' => array(
		'from' => 'bird@oiseauthere.com',
		'to' => 'bird@oiseauthere.com'
	),
	'fields' => array(
		'custom_U31856' => array(
			'order' => 1,
			'type' => 'string',
			'label' => '稱呼：',
			'required' => true,
			'errors' => array(
				'required' => '欄位「稱呼：」為必填。'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => '電子郵件信箱：',
			'required' => true,
			'errors' => array(
				'required' => '欄位「電子郵件信箱：」為必填。',
				'format' => '「電子郵件信箱：」欄位有無效的電子郵件。'
			)
		),
		'custom_U31864' => array(
			'order' => 3,
			'type' => 'string',
			'label' => '訊息：',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
